# Generated by Django 4.2 on 2023-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_test_file_alter_test_id_alter_test_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='file',
        ),
        migrations.AlterField(
            model_name='test',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
